// <auto-generated />
using System;
using HutechPM.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HutechNote.Data.Migrations
{
    [DbContext(typeof(HutechNoteDbContext))]
    [Migration("20231030054354_update_database_30102023_v1")]
    partial class update_database_30102023_v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HutechPM.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("projectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("dateEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_end");

                    b.Property<DateTime>("dateStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_start");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("project_name");

                    b.HasKey("projectId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.ProjectAttachment", b =>
                {
                    b.Property<Guid>("acttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("acttachment_id");

                    b.Property<DateTime>("dateCreate")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_create");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acttachment_name");

                    b.Property<Guid>("taskprojectTaskid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("acttachmentId");

                    b.HasIndex("taskprojectTaskid");

                    b.ToTable("ProjectAttachment");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.ProjectDetail", b =>
                {
                    b.Property<Guid>("projectDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_detail_id");

                    b.Property<int>("projectRole")
                        .HasColumnType("int")
                        .HasColumnName("project_role");

                    b.Property<Guid?>("project_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("timeJoin")
                        .HasColumnType("datetime2")
                        .HasColumnName("time_join");

                    b.Property<DateTime>("timeLeft")
                        .HasColumnType("datetime2")
                        .HasColumnName("time_left");

                    b.Property<Guid?>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("projectDetailId");

                    b.HasIndex("project_id");

                    b.HasIndex("user_id");

                    b.ToTable("ProjectDetail");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("projectTaskid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_task_id");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("estimate")
                        .HasColumnType("int")
                        .HasColumnName("estimate");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("taskName");

                    b.Property<Guid>("project_detail_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("remaining")
                        .HasColumnType("int")
                        .HasColumnName("remaining");

                    b.Property<int>("taskStatus")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("projectTaskid");

                    b.HasIndex("project_detail_id");

                    b.ToTable("ProjectTask");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.User", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int?>("UserRoleId")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("full_name");

                    b.Property<bool>("gender")
                        .HasColumnType("bit")
                        .HasColumnName("gender");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("phone");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("userId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_role_name");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.ProjectAttachment", b =>
                {
                    b.HasOne("HutechPM.Data.Entities.ProjectTask", "task")
                        .WithMany("projectAttachments")
                        .HasForeignKey("taskprojectTaskid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("task");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.ProjectDetail", b =>
                {
                    b.HasOne("HutechPM.Data.Entities.Project", "project")
                        .WithMany("ApplicationProjectDetails")
                        .HasForeignKey("project_id");

                    b.HasOne("HutechPM.Data.Entities.User", "user")
                        .WithMany("ApplicationProjectDetails")
                        .HasForeignKey("user_id");

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.ProjectTask", b =>
                {
                    b.HasOne("HutechPM.Data.Entities.ProjectDetail", "projectDetail")
                        .WithMany("projectTasks")
                        .HasForeignKey("project_detail_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("projectDetail");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.User", b =>
                {
                    b.HasOne("HutechPM.Data.Entities.UserRole", null)
                        .WithMany("users")
                        .HasForeignKey("UserRoleId");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.Project", b =>
                {
                    b.Navigation("ApplicationProjectDetails");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.ProjectDetail", b =>
                {
                    b.Navigation("projectTasks");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.ProjectTask", b =>
                {
                    b.Navigation("projectAttachments");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.User", b =>
                {
                    b.Navigation("ApplicationProjectDetails");
                });

            modelBuilder.Entity("HutechPM.Data.Entities.UserRole", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
